"""Scalable ISO/IEC 27001:2022 Catalog and Multi-Project Registry for GEAP."""

ACTIVE_PROJECTS = [
    {
        "project_id": "agentic-grc-cd06",
        "environment": "PRODUCTION",
        "region": "us-central1",
        "status": "AUDITED",
        "score": 100.0,
    },
    {
        "project_id": "agentic-grc-staging",
        "environment": "STAGING",
        "region": "us-central1",
        "status": "COMPLIANT",
        "score": 98.2,
    },
    {
        "project_id": "agentic-grc-data-lake",
        "environment": "ANALYTICS",
        "region": "us-east4",
        "status": "COMPLIANT",
        "score": 100.0,
    },
]

ISO_27001_CATALOG = [
    # A.5 Organizational Controls
    {
        "id": "A.5.1",
        "name": "Políticas de Segurança da Informação",
        "theme": "A.5 Organizacional",
        "description": "Conjunto de políticas aprovadas pela direção, publicadas e comunicadas a colaboradores e partes interessadas.",
        "gcp_mapping": "Google Cloud Resource Manager & Organization Policies",
        "status": "COMPLIANT",
        "phase": "Fase 3: Governança & Políticas",
        "evidence": "Doc Ref: POL-SEC-01 (Zero-Copy Drive Sync)",
        "severity": "LOW",
    },
    {
        "id": "A.5.2",
        "name": "Funções e Responsabilidades de Segurança",
        "theme": "A.5 Organizacional",
        "description": "Definição formal de papéis e segregação com base em privilégio mínimo.",
        "gcp_mapping": "Cloud IAM Role Bindings & Privileged Access Manager",
        "status": "COMPLIANT",
        "phase": "Fase 1: Descoberta de Ativos & IAM",
        "evidence": "IAM least-privilege matrix verified",
        "severity": "LOW",
    },
    {
        "id": "A.5.3",
        "name": "Segregação de Funções (SoD)",
        "theme": "A.5 Organizacional",
        "description": "Funções conflitantes e áreas de responsabilidade segregadas para prevenir modificações não autorizadas.",
        "gcp_mapping": "Separated Deployer & Auditor Service Accounts",
        "status": "COMPLIANT",
        "phase": "Fase 1: Descoberta de Ativos & IAM",
        "evidence": "sa-auditor vs sa-deployer roles segregated",
        "severity": "MEDIUM",
    },
    {
        "id": "A.5.7",
        "name": "Inteligência sobre Ameaças (Threat Intelligence)",
        "theme": "A.5 Organizacional",
        "description": "Informações sobre ameaças de segurança coletadas e analisadas para gerar inteligência de defesa.",
        "gcp_mapping": "Google SecOps & Mandiant Threat Intelligence Feeds",
        "status": "COMPLIANT",
        "phase": "Fase 2: Auditoria Técnica Profunda",
        "evidence": "BigQuery log sink to Mandiant active",
        "severity": "MEDIUM",
    },
    {
        "id": "A.5.9",
        "name": "Inventário de Informações e Outros Ativos",
        "theme": "A.5 Organizacional",
        "description": "Inventário contínuo de ativos de informação identificado, atualizado e mantido.",
        "gcp_mapping": "Cloud Asset Inventory API (Continuous Telemetry)",
        "status": "COMPLIANT",
        "phase": "Fase 1: Descoberta de Ativos & IAM",
        "evidence": "Real-time Asset Ingestion mapped",
        "severity": "LOW",
    },
    {
        "id": "A.5.15",
        "name": "Controle de Acesso Lógico",
        "theme": "A.5 Organizacional",
        "description": "Regras e direitos de acesso controlados de acordo com os requisitos de negócio e classificação.",
        "gcp_mapping": "IAM Recommender & Conditional IAM Policies",
        "status": "COMPLIANT",
        "phase": "Fase 1: Descoberta de Ativos & IAM",
        "evidence": "Zero standing unauthenticated access",
        "severity": "HIGH",
    },
    {
        "id": "A.5.23",
        "name": "Segurança da Informação no Uso de Nuvem",
        "theme": "A.5 Organizacional",
        "description": "Processos de aquisição, uso, gestão e saída de serviços de computação em nuvem estabelecidos.",
        "gcp_mapping": "Cloud Storage PAP & Uniform Bucket-Level Access (UBLA)",
        "status": "COMPLIANT",
        "phase": "Fase 2: Auditoria Técnica Profunda",
        "evidence": "Public Access Prevention enforced on all buckets",
        "severity": "CRITICAL",
    },
    {
        "id": "A.5.28",
        "name": "Gestão e Resposta a Incidentes",
        "theme": "A.5 Organizacional",
        "description": "Procedimentos para reportar, responder e registrar incidentes de segurança da informação.",
        "gcp_mapping": "Cloud Monitoring Alerts & Pub/Sub Incident Bus",
        "status": "COMPLIANT",
        "phase": "Fase 2: Auditoria Técnica Profunda",
        "evidence": "Automated incident response playbooks configured",
        "severity": "HIGH",
    },

    # A.6 People Controls
    {
        "id": "A.6.1",
        "name": "Triagem e Verificação Pré-Contratação",
        "theme": "A.6 Pessoas",
        "description": "Verificações de antecedentes em candidatos realizadas de acordo com as leis e ética aplicáveis.",
        "gcp_mapping": "HR Zero-Copy Connector (Workday / Identity Sync)",
        "status": "COMPLIANT",
        "phase": "Fase 3: Governança & Políticas",
        "evidence": "Screening records verified at source",
        "severity": "LOW",
    },
    {
        "id": "A.6.3",
        "name": "Conscientização e Treinamento em Segurança",
        "theme": "A.6 Pessoas",
        "description": "Colaboradores recebem treinamento apropriado e atualizações regulares sobre segurança da informação.",
        "gcp_mapping": "Corporate LMS Zero-Copy Integration",
        "status": "COMPLIANT",
        "phase": "Fase 3: Governança & Políticas",
        "evidence": "98.4% workforce training completion rate verified",
        "severity": "MEDIUM",
    },
    {
        "id": "A.6.7",
        "name": "Segurança no Trabalho Remoto",
        "theme": "A.6 Pessoas",
        "description": "Medidas de proteção implementadas para proteger informações acessadas em regime de trabalho remoto.",
        "gcp_mapping": "BeyondCorp Enterprise Context-Aware Access & Chrome Enterprise",
        "status": "COMPLIANT",
        "phase": "Fase 1: Descoberta de Ativos & IAM",
        "evidence": "Device mTLS certificate authentication enforced",
        "severity": "HIGH",
    },

    # A.7 Physical Controls
    {
        "id": "A.7.1",
        "name": "Perímetros Físicos de Segurança",
        "theme": "A.7 Físico",
        "description": "Perímetros de segurança definidos e usados para proteger áreas que contenham informações e ativos.",
        "gcp_mapping": "Google Cloud Data Center SOC 1/2/3 Certifications",
        "status": "COMPLIANT",
        "phase": "Fase 3: Governança & Políticas",
        "evidence": "GCP Data Center ISO 27001 Compliance Attestation",
        "severity": "LOW",
    },
    {
        "id": "A.7.4",
        "name": "Monitoramento de Segurança Física",
        "theme": "A.7 Físico",
        "description": "Locais de operação monitorados continuamente por câmeras de segurança, alarmes e rondas de vigilância.",
        "gcp_mapping": "Google Shared Responsibility Model & Compliance Reports Manager",
        "status": "COMPLIANT",
        "phase": "Fase 3: Governança & Políticas",
        "evidence": "Google physical telemetry third-party audited",
        "severity": "LOW",
    },
    {
        "id": "A.7.8",
        "name": "Proteção de Equipamentos e Cabos",
        "theme": "A.7 Físico",
        "description": "Equipamentos protegidos contra ameaças físicas e ambientais com fornecimento contínuo de energia.",
        "gcp_mapping": "Redundant Power & Dedicated Subsea Cable Infrastructure",
        "status": "COMPLIANT",
        "phase": "Fase 3: Governança & Políticas",
        "evidence": "Multi-grid power failover attested",
        "severity": "MEDIUM",
    },

    # A.8 Technological Controls
    {
        "id": "A.8.1",
        "name": "Dispositivos de Usuários Finais (Endpoint)",
        "theme": "A.8 Tecnológico",
        "description": "Informações armazenadas ou processadas por dispositivos de usuários finais protegidas contra riscos.",
        "gcp_mapping": "Endpoint Verification & ChromeOS Trusted Platform Module",
        "status": "COMPLIANT",
        "phase": "Fase 1: Descoberta de Ativos & IAM",
        "evidence": "100% managed fleet with full disk encryption",
        "severity": "HIGH",
    },
    {
        "id": "A.8.2",
        "name": "Direitos de Acesso Privilegiado",
        "theme": "A.8 Tecnológico",
        "description": "Alocação e uso de direitos de acesso privilegiado rigorosamente restritos e controlados.",
        "gcp_mapping": "Just-In-Time (JIT) PAM & Short-Lived OAuth Tokens",
        "status": "COMPLIANT",
        "phase": "Fase 1: Descoberta de Ativos & IAM",
        "evidence": "No persistent root/owner service keys",
        "severity": "CRITICAL",
    },
    {
        "id": "A.8.9",
        "name": "Gerenciamento de Configuração (IaC)",
        "theme": "A.8 Tecnológico",
        "description": "Configurações de nuvem estabelecidas, documentadas e monitoradas contra desvios de segurança.",
        "gcp_mapping": "Terraform / Ansible Static Analyzer & Cloud Build Policy Check",
        "status": "COMPLIANT",
        "phase": "Fase 2: Auditoria Técnica Profunda",
        "evidence": "IaC scanner verified 0 high drift in repo",
        "severity": "HIGH",
    },
    {
        "id": "A.8.12",
        "name": "Prevenção de Vazamento de Dados (DLP)",
        "theme": "A.8 Tecnológico",
        "description": "Medidas aplicadas para prevenir a exfiltração não autorizada de dados confidenciais.",
        "gcp_mapping": "VPC Service Controls Perimeters & Cloud DLP API",
        "status": "COMPLIANT",
        "phase": "Fase 2: Auditoria Técnica Profunda",
        "evidence": "Perimeter enforced on Storage & BigQuery",
        "severity": "CRITICAL",
    },
    {
        "id": "A.8.16",
        "name": "Atividades de Monitoramento e Logs",
        "theme": "A.8 Tecnológico",
        "description": "Redes, sistemas e aplicações monitorados para comportamento anômalo com registros arquivados.",
        "gcp_mapping": "Cloud Logging Immutable Buckets & Retention Locks",
        "status": "COMPLIANT",
        "phase": "Fase 2: Auditoria Técnica Profunda",
        "evidence": "365-day immutable audit log sink active",
        "severity": "HIGH",
    },
    {
        "id": "A.8.20",
        "name": "Segurança de Redes",
        "theme": "A.8 Tecnológico",
        "description": "Redes de computadores protegidas, gerenciadas e controladas para salvaguardar dados em trânsito.",
        "gcp_mapping": "Cloud Armor WAF, Private Google Access, Cloud NAT",
        "status": "COMPLIANT",
        "phase": "Fase 2: Auditoria Técnica Profunda",
        "evidence": "Zero public IP ingress on workload pods",
        "severity": "CRITICAL",
    },
    {
        "id": "A.8.24",
        "name": "Uso de Criptografia",
        "theme": "A.8 Tecnológico",
        "description": "Regras para o uso eficaz de criptografia e gerenciamento de chaves criptográficas implementadas.",
        "gcp_mapping": "Cloud KMS HSM Keys & 90-day Automatic Rotation",
        "status": "COMPLIANT",
        "phase": "Fase 2: Auditoria Técnica Profunda",
        "evidence": "HSM Protection Level + 60-day rotation period",
        "severity": "CRITICAL",
    },
    {
        "id": "A.8.28",
        "name": "Codificação e Desenvolvimento Seguro",
        "theme": "A.8 Tecnológico",
        "description": "Princípios de desenvolvimento seguro de software aplicados a todos os desenvolvimentos internos.",
        "gcp_mapping": "Artifact Registry Vulnerability Scanning & Binary Authorization",
        "status": "COMPLIANT",
        "phase": "Fase 2: Auditoria Técnica Profunda",
        "evidence": "Container base images scanned; 0 zero-day vulns",
        "severity": "HIGH",
    },

    # ISO/IEC 27001:2022 / Amd 1:2024 Climate Action
    {
        "id": "Amd 1:2024 Cl. 4.1",
        "name": "Ação Climática no Contexto da Organização",
        "theme": "Amd 1:2024 Clima",
        "description": "Determinação formal de se as mudanças climáticas e eventos meteorológicos extremos são questões relevantes para o SGSI.",
        "gcp_mapping": "Multiregional Topology (us-central1 / us-east4) & Climate Risk Registry",
        "status": "COMPLIANT",
        "phase": "Fase 3: Governança & Políticas",
        "evidence": "Climate risk matrix integrated into ISMS risk register",
        "severity": "HIGH",
    },
    {
        "id": "Amd 1:2024 Cl. 4.2",
        "name": "Requisitos de Partes Interessadas em Mudanças Climáticas",
        "theme": "Amd 1:2024 Clima",
        "description": "Identificação dos requisitos regulatórios, contratuais e de clientes relacionados a eventos climáticos e resiliência.",
        "gcp_mapping": "Automated Cross-Region Failover Testing & RTO/RPO SLA",
        "status": "COMPLIANT",
        "phase": "Fase 3: Governança & Políticas",
        "evidence": "Semiannual disaster recovery failover executed successfully",
        "severity": "HIGH",
    },
]