"""FinOps Engine for Agentic GRC & Gemini Enterprise Agent Platform.

Tracks:
- Prompt tokens, cached prompt tokens, completion tokens across agents and subagents.
- Real-time cost estimation ($ USD and R$ BRL) using Vertex AI / Gemini 2.5 rates.
- Context Caching ROI and savings calculation.
- Phase-by-phase financial breakdown (Fases 1 a 4).
"""

from typing import Dict, List, Any, Optional
from datetime import datetime, timezone

# Vertex AI Gemini Pricing per 1M tokens (USD)
MODEL_PRICING = {
    "gemini-2.5-pro": {
        "name": "Gemini 2.5 Pro",
        "prompt_rate": 1.25,        # .25 per 1M input tokens
        "cached_rate": 0.3125,      # zsh.3125 per 1M cached prompt tokens (75% savings)
        "completion_rate": 5.00,    # .00 per 1M output tokens
    },
    "gemini-2.5-flash": {
        "name": "Gemini 2.5 Flash",
        "prompt_rate": 0.075,       # $0.075 per 1M input tokens
        "cached_rate": 0.01875,     # $0.01875 per 1M cached prompt tokens
        "completion_rate": 0.30,    # $0.30 per 1M output tokens
    },
    "gemini-3.5-flash": {
        "name": "Gemini 3.5 Flash",
        "prompt_rate": 0.050,       # $0.050 per 1M input tokens
        "cached_rate": 0.0125,      # $0.0125 per 1M cached prompt tokens
        "completion_rate": 0.20,    # $0.20 per 1M output tokens
    },
    "text-embedding-005": {
        "name": "Text Embedding 005",
        "prompt_rate": 0.025,
        "cached_rate": 0.005,
        "completion_rate": 0.0,
    },
}

USD_TO_BRL_RATE = 5.70


class AgentFinOpsRecord:
    def __init__(
        self,
        agent_id: str,
        name: str,
        category: str,
        model_key: str,
        invocations: int = 0,
        prompt_tokens: int = 0,
        cached_tokens: int = 0,
        completion_tokens: int = 0,
    ):
        self.agent_id = agent_id
        self.name = name
        self.category = category
        self.model_key = model_key
        self.invocations = invocations
        self.prompt_tokens = prompt_tokens
        self.cached_tokens = cached_tokens
        self.completion_tokens = completion_tokens

    @property
    def total_tokens(self) -> int:
        return self.prompt_tokens + self.cached_tokens + self.completion_tokens

    @property
    def cost_usd(self) -> float:
        pricing = MODEL_PRICING.get(self.model_key, MODEL_PRICING["gemini-2.5-flash"])
        cost = (
            self.prompt_tokens * pricing["prompt_rate"]
            + self.cached_tokens * pricing["cached_rate"]
            + self.completion_tokens * pricing["completion_rate"]
        ) / 1_000_000
        return round(cost, 4)

    @property
    def cost_brl(self) -> float:
        return round(self.cost_usd * USD_TO_BRL_RATE, 2)

    @property
    def savings_usd(self) -> float:
        """Savings generated by Gemini Context Caching vs uncached re-reading."""
        pricing = MODEL_PRICING.get(self.model_key, MODEL_PRICING["gemini-2.5-flash"])
        uncached_cost = (self.cached_tokens * pricing["prompt_rate"]) / 1_000_000
        cached_cost = (self.cached_tokens * pricing["cached_rate"]) / 1_000_000
        return round(max(0.0, uncached_cost - cached_cost), 4)

    def to_dict(self) -> Dict[str, Any]:
        pricing = MODEL_PRICING.get(self.model_key, MODEL_PRICING["gemini-2.5-flash"])
        return {
            "agent_id": self.agent_id,
            "name": self.name,
            "category": self.category,
            "model": pricing["name"],
            "model_key": self.model_key,
            "invocations": self.invocations,
            "prompt_tokens": self.prompt_tokens,
            "cached_tokens": self.cached_tokens,
            "completion_tokens": self.completion_tokens,
            "total_tokens": self.total_tokens,
            "cost_usd": self.cost_usd,
            "cost_brl": self.cost_brl,
            "savings_usd": self.savings_usd,
        }


class FinOpsTracker:
    def __init__(self):
        self.records: Dict[str, AgentFinOpsRecord] = {}
        self.phase_metrics: Dict[str, Dict[str, Any]] = {
            "Fase 1: Triagem Zero-Copy": {
                "description": "Ingestão semântica e mapeamento documental",
                "tokens": 420000,
                "cost_usd": 0.42,
            },
            "Fase 2: Telemetria Técnica GCP": {
                "description": "Auditoria de IAM, Cloud KMS, SCC e Workload Identity",
                "tokens": 680000,
                "cost_usd": 0.88,
            },
            "Fase 3: Testes de Eficácia & Drift": {
                "description": "Verificação ativa de controles ISO 27001 e simulação",
                "tokens": 390000,
                "cost_usd": 0.54,
            },
            "Fase 4: Parecer Executivo & Selo": {
                "description": "Orquestração executiva, síntese e assinatura criptográfica",
                "tokens": 352650,
                "cost_usd": 1.64,
            },
        }
        self.seed_defaults()

    def seed_defaults(self):
        """Initial realistic telemetry for continuous GRC audit runs."""
        initial_agents = [
            AgentFinOpsRecord(
                agent_id="lead-auditor",
                name="Lead Auditor Orquestrador",
                category="Orquestração Executiva",
                model_key="gemini-2.5-pro",
                invocations=42,
                prompt_tokens=480000,
                cached_tokens=320000,
                completion_tokens=185000,
            ),
            AgentFinOpsRecord(
                agent_id="subagent-a5",
                name="Subagente A.5 Organizacional",
                category="Controles ISO 27001",
                model_key="gemini-2.5-flash",
                invocations=37,
                prompt_tokens=240000,
                cached_tokens=190000,
                completion_tokens=68000,
            ),
            AgentFinOpsRecord(
                agent_id="subagent-a6",
                name="Subagente A.6 Pessoas & RH",
                category="Controles ISO 27001",
                model_key="gemini-2.5-flash",
                invocations=18,
                prompt_tokens=95000,
                cached_tokens=80000,
                completion_tokens=32000,
            ),
            AgentFinOpsRecord(
                agent_id="subagent-a7",
                name="Subagente A.7 Físico & Ambientes",
                category="Controles ISO 27001",
                model_key="gemini-2.5-flash",
                invocations=14,
                prompt_tokens=78000,
                cached_tokens=65000,
                completion_tokens=28000,
            ),
            AgentFinOpsRecord(
                agent_id="subagent-a8",
                name="Subagente A.8 Tecnológico & Cripto",
                category="Controles ISO 27001",
                model_key="gemini-2.5-flash",
                invocations=56,
                prompt_tokens=360000,
                cached_tokens=290000,
                completion_tokens=112000,
            ),
            AgentFinOpsRecord(
                agent_id="gcp-telemetry",
                name="GCP Telemetry & Assets Scanner",
                category="Telemetria em Nuvem",
                model_key="gemini-2.5-flash",
                invocations=64,
                prompt_tokens=310000,
                cached_tokens=250000,
                completion_tokens=85000,
            ),
            AgentFinOpsRecord(
                agent_id="zero-copy-ingestion",
                name="Zero-Copy Evidence Ingestion",
                category="Ingestão & RAG",
                model_key="gemini-2.5-flash",
                invocations=28,
                prompt_tokens=180000,
                cached_tokens=140000,
                completion_tokens=45000,
            ),
            AgentFinOpsRecord(
                agent_id="semantic-embeddings",
                name="Audit Knowledge Embeddings",
                category="Vetorização Semântica",
                model_key="text-embedding-005",
                invocations=120,
                prompt_tokens=520000,
                cached_tokens=0,
                completion_tokens=0,
            ),
        ]
        for ag in initial_agents:
            self.records[ag.agent_id] = ag

    def record_usage(
        self,
        agent_id: str,
        prompt_tokens: int,
        completion_tokens: int,
        cached_tokens: int = 0,
        model_key: str = "gemini-2.5-flash",
        name: Optional[str] = None,
        category: Optional[str] = None,
    ):
        if agent_id not in self.records:
            self.records[agent_id] = AgentFinOpsRecord(
                agent_id=agent_id,
                name=name or agent_id.replace("-", " ").title(),
                category=category or "Subagente Dinâmico",
                model_key=model_key,
            )
        rec = self.records[agent_id]
        rec.invocations += 1
        rec.prompt_tokens += prompt_tokens
        rec.cached_tokens += cached_tokens
        rec.completion_tokens += completion_tokens

    def get_summary(self) -> Dict[str, Any]:
        agents_data = [rec.to_dict() for rec in self.records.values()]
        
        total_prompt = sum(r["prompt_tokens"] for r in agents_data)
        total_cached = sum(r["cached_tokens"] for r in agents_data)
        total_completion = sum(r["completion_tokens"] for r in agents_data)
        total_tokens = total_prompt + total_cached + total_completion
        total_invocations = sum(r["invocations"] for r in agents_data)
        
        total_cost_usd = round(sum(r["cost_usd"] for r in agents_data), 4)
        total_cost_brl = round(total_cost_usd * USD_TO_BRL_RATE, 2)
        total_savings_usd = round(sum(r["savings_usd"] for r in agents_data), 4)
        total_savings_brl = round(total_savings_usd * USD_TO_BRL_RATE, 2)
        
        cache_hit_ratio = round((total_cached / (total_prompt + total_cached) * 100) if (total_prompt + total_cached) > 0 else 0, 1)
        cost_per_control_usd = round(total_cost_usd / 93, 4)

        return {
            "summary": {
                "total_cost_usd": total_cost_usd,
                "total_cost_brl": total_cost_brl,
                "total_savings_usd": total_savings_usd,
                "total_savings_brl": total_savings_brl,
                "total_tokens": total_tokens,
                "total_prompt_tokens": total_prompt,
                "total_cached_tokens": total_cached,
                "total_completion_tokens": total_completion,
                "total_invocations": total_invocations,
                "cache_hit_ratio_percent": cache_hit_ratio,
                "cost_per_control_usd": cost_per_control_usd,
                "usd_to_brl_rate": USD_TO_BRL_RATE,
                "monthly_quota_usd": 50.00,
                "quota_used_percent": round((total_cost_usd / 50.00) * 100, 1),
                "timestamp": datetime.now(timezone.utc).isoformat(),
            },
            "agents": agents_data,
            "phases": self.phase_metrics,
            "pricing_reference": MODEL_PRICING,
        }


finops_tracker = FinOpsTracker()
